package barrysoft.twinkle.view;

public enum UpdaterEventType 
{
	CHECKING_UPDATES,
	CHECKING_COMPLETED,
	NEW_VERSION_FOUND,
	DOWNLOAD_STARTED,
	DOWNLOAD_PROGRESS,
	DOWNLOAD_ENDED,
	EXTRACTION_STARTED,
	EXTRACTION_ENDED,
	VALIDATION_STARTED,
	VALIDATION_ENDED,
	UPDATE_COMPLETED,
	ERROR_OCCURRED
};
